#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0xC36CDCB4DF00C68C (infra-root@openstack.org)
#
Name     : ironic
Version  : 11.1.0
Release  : 2
URL      : https://tarballs.openstack.org/ironic/ironic-11.1.0.tar.gz
Source0  : https://tarballs.openstack.org/ironic/ironic-11.1.0.tar.gz
Source99 : https://tarballs.openstack.org/ironic/ironic-11.1.0.tar.gz.asc
Summary  : OpenStack Bare Metal Provisioning
Group    : Development/Tools
License  : Apache-2.0
Requires: ironic-bin
Requires: ironic-config
Requires: ironic-python3
Requires: ironic-license
Requires: ironic-python
Requires: Jinja2
Requires: SQLAlchemy
Requires: Sphinx
Requires: WSME
Requires: WebOb
Requires: alembic
Requires: automaton
Requires: eventlet
Requires: futurist
Requires: ironic-lib
Requires: jsonpatch
Requires: jsonschema
Requires: keystoneauth1
Requires: keystonemiddleware
Requires: openstackdocstheme
Requires: os-api-ref
Requires: os-traits
Requires: oslo.concurrency
Requires: oslo.config
Requires: oslo.context
Requires: oslo.db
Requires: oslo.i18n
Requires: oslo.log
Requires: oslo.messaging
Requires: oslo.middleware
Requires: oslo.policy
Requires: oslo.reports
Requires: oslo.rootwrap
Requires: oslo.serialization
Requires: oslo.service
Requires: oslo.utils
Requires: oslo.versionedobjects
Requires: osprofiler
Requires: pbr
Requires: pecan
Requires: psutil
Requires: pysendfile
Requires: python-cinderclient
Requires: python-glanceclient
Requires: python-mock
Requires: python-neutronclient
Requires: python-swiftclient
Requires: pytz
Requires: reno
Requires: requests
Requires: retrying
Requires: rfc3986
Requires: six
Requires: stevedore
Requires: tooz
BuildRequires : WSME
BuildRequires : buildreq-distutils3
BuildRequires : keystonemiddleware
BuildRequires : oslo.versionedobjects
BuildRequires : pbr
BuildRequires : pluggy
BuildRequires : py-python
BuildRequires : pytest
BuildRequires : retrying
BuildRequires : tooz
BuildRequires : tox
BuildRequires : virtualenv

%description
Team and repository tags
        ========================

%package bin
Summary: bin components for the ironic package.
Group: Binaries
Requires: ironic-config
Requires: ironic-license

%description bin
bin components for the ironic package.


%package config
Summary: config components for the ironic package.
Group: Default

%description config
config components for the ironic package.


%package license
Summary: license components for the ironic package.
Group: Default

%description license
license components for the ironic package.


%package python
Summary: python components for the ironic package.
Group: Default
Requires: ironic-python3

%description python
python components for the ironic package.


%package python3
Summary: python3 components for the ironic package.
Group: Default
Requires: python3-core

%description python3
python3 components for the ironic package.


%prep
%setup -q -n ironic-11.1.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1533908468
python3 setup.py build -b py3

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
PYTHONPATH=%{buildroot}/usr/lib/python3.7/site-packages python3 setup.py test || :
%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/ironic
cp LICENSE %{buildroot}/usr/share/doc/ironic/LICENSE
python3 -tt setup.py build -b py3 install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/ironic-api
/usr/bin/ironic-api-wsgi
/usr/bin/ironic-conductor
/usr/bin/ironic-dbsync
/usr/bin/ironic-rootwrap

%files config
%defattr(-,root,root,-)
%config /usr/etc/ironic/rootwrap.conf
%config /usr/etc/ironic/rootwrap.d/ironic-images.filters
%config /usr/etc/ironic/rootwrap.d/ironic-lib.filters
%config /usr/etc/ironic/rootwrap.d/ironic-utils.filters

%files license
%defattr(-,root,root,-)
/usr/share/doc/ironic/LICENSE

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
